import type {Metadata} from "next";
import Header from "@/components/Home/Header";


export const metadata: Metadata = {
    title: "简逸home",
    description: "Generated by create next app",
};

export default function Layout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section>
            <Header />
            {children}
        </section>
    );
}
