'use client'

import type {Metadata} from "next";
import Header from "@/components/Home/Header";
import {useEffect} from "react";
// export const metadata: Metadata = {
//     title: "简逸home",
//     description: "Generated by create next app",
// };

export default function Layout({
                                   children,
                               }: Readonly<{
    children: React.ReactNode;
}>) {
    useEffect(() => {
        const socket = new WebSocket('ws://localhost:8080'); // 根据你的服务器地址和端口进行修改
    }, []);
    return (
        <section>
            <Header/>
            {children}
        </section>
    );
}
